### ISSUE TITLE
H has no prupose

### ISSUE THREAD

**Issue by skoehler** [ilanschnell/perfect-hash#1]
I don't see the purpose of the H array. The generated perfect hash function is minimal and order preserving, in other words: the i-th key should have hash value i-1. In other words, the check at the end should always be

````
for i, k in enumerate(K):
    assert perfect_hash(k) == i
````

Am I missing something and your script also supports generating hash function which are non-minimal or not order preserving?

**Comment by ilanschnell** [comment]
From an end user perspective `H` has almost no purpose, (unless the `--hashcol`) option is used.  I originally wrote the code very general and allowed for providing desired hash values also.  I know realize that this was not a good idea, as it leads to confusion and over complicated code.

Therefore, I removed the `--hashcol` option, and changed all code to always assume the hash value of a key its location in the given list of keys.
