### ISSUE TITLE
wrong modulo in function perfect_hash

### ISSUE THREAD

**Issue by skoehler** [ilanschnell/perfect-hash#3]
With version 0.2.1, I get the following output:

````
# =======================================================================
# ================= Python code for perfect hash function ===============
# =======================================================================

G = [0, 5, 1, 3, 0, 2]

S1 = [2, 3, 2]
S2 = [1, 1, 3]

def hash_f(key, T):
    return sum(T[i % 3] * ord(c) for i, c in enumerate(str(key))) % 6

def perfect_hash(key):
    return (G[hash_f(key, S1)] + G[hash_f(key, S2)]) % 6

# ============================ Sanity check =============================

K = ["a", "bc", "bar", "foo"]
H = [0, 1, 2, 3]

assert len(K) == len(H) == 4

for k, h in zip(K, H):
    assert perfect_hash(k) == h
````

I don't understand why in function `perfect_hash` the module 6 is used. According to the research paper, the modulo should be m which is the number of word. In the example above, the number of words is 4. So the code seems to contradict the research paper.

The asserts pass, so certainly the hash values are 0 to 3 not including 4 or 5.

**Comment by skoehler** [comment]
I partially withdraw my comment. Yes, the paper uses m (the number of words) as the modulo.
But this is only the minimum modulo. In fact, when filling in the values of g along the edges of the acyclic graph, one can use any modulo larger or equal to m. In particular, for efficiency reasons, one might want to use a power of 2 as the modulo. That will work just fine.

However, when using a modulo larger than m it needs to be documented that the hash function may return values which are too large.

**Comment by ilanschnell** [comment]
Yes, the modulo (NG) does not have to be equal to the number of keys (NK), and you are correct that this is done because of efficiency.

When the modulo is larger, the (perfect) hash function may only return values which are too large when the key is not in the "training" list.  I will add a note about this fact.
