### ISSUE TITLE
Clarify license of the output

### ISSUE THREAD

**Issue by bluetech** [ilanschnell/perfect-hash#5]
Hi,

This is a nice package and seems to work well. I'm considering utilizing it in a project (libxkbcommon).

Do you think it would be possible to add a clarification on the license on the *output* of the program? For example, gperf [says this](https://www.gnu.org/software/gperf/manual/gperf.html#Output-Copyright):

>  gperf is under GPL, but that does not cause the output produced by gperf to be under GPL. The reason is that the output contains only small pieces of text that come directly from gperf's source code – only about 7 lines long, too small for being significant –, and therefore the output is not a “work based on gperf” (in the sense of the GPL version 3).
>
> On the other hand, the output produced by gperf contains essentially all of the input file. Therefore the output is a “derivative work” of the input (in the sense of U.S. copyright law); and its copyright status depends on the copyright of the input. For most software licenses, the result is that the the output is under the same license, with the same copyright holder, as the input that was passed to gperf.

It would be great if the README or similar could contain a similar paragraph.

Thanks.

**Comment by bluetech** [comment]
Also, the LICENSE.txt file has a couple of placeholders, `<organization>` and `<COPYRIGHT HOLDER>`.

**Comment by ilanschnell** [comment]
Thanks, for using perfect-hash!  I've added a paragraph to the readme, saying essentially the same as gperf regarding the output of the program: https://github.com/ilanschnell/perfect-hash#license-of-output

**Comment by bluetech** [comment]
Thank you!

The library works great, and the algorithm is beautiful.

If you're interested, I use it here: https://github.com/xkbcommon/libxkbcommon/commit/68e69b7deb8d0d38758a7a68c76892b90e3fccc9

I made a small tweak to ensure to ensure a fast AND is used instead of a costly modulo: https://github.com/xkbcommon/libxkbcommon/commit/45b1ca22052b79c83bd96b7c5828add156768b8e

When I have some time, I'll also try to use a couple of faster hash functions.

**Comment by ilanschnell** [comment]
Great!  I'm also happy when people find the libraries I write useful.

Ah, I see.  Your tweak is making the character salt slightly larger than necessary, but it'll give the advantage that `% 32` is fast.  Good job!

The library allows developing new hash functions without too much effort (in particular without changing `perfect_hash.py`).  I've played with:
  * DEK hash: https://github.com/ilanschnell/perfect-hash/blob/master/examples/dekhash.py
  * Python's own hash function: https://github.com/ilanschnell/perfect-hash/blob/master/examples/pythonhash.py

Happy hacking!
